version: '3.8'
services:
    mysql:
        image: mysql:latest
        container_name: sql
        expose:
            - "3306"
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
        volumes: 
            - ./scripts:/scripts
            