version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        expose:
            - "5432"
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: db
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            TZ: "Asia/Tokyo"
        volumes: 
            - ./scripts:/scripts
            - ./init:/docker-entrypoint-initdb.d
